import React from 'react';
import Navbar from '../components/Navbar';
import Hero from '../components/Hero';

const Home = () => {
    return (
        <div className="min-h-screen bg-void-black text-white selection:bg-neon-cyan selection:text-black">
            <Navbar />
            <Hero />

            {/* Placeholder for other sections */}
            <div id="features" className="py-20 container mx-auto px-6">
                <h2 className="text-4xl font-bold mb-10 text-center">Game Features</h2>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                    <div className="bg-slate-grey p-6 rounded-2xl border border-white/5">
                        <img src="/images/gameplay_concept_map.png" alt="GPS Gameplay" className="w-full h-48 object-cover rounded-lg mb-4" />
                        <h3 className="text-2xl font-bold mb-2">Real-World Territory</h3>
                        <p className="text-gray-400">Walk to claim land. Your footsteps define your empire.</p>
                    </div>
                    <div className="bg-slate-grey p-6 rounded-2xl border border-white/5">
                        <img src="/images/gameplay_concept_ruins.png" alt="Ruins" className="w-full h-48 object-cover rounded-lg mb-4" />
                        <h3 className="text-2xl font-bold mb-2">Scavenge Ruins</h3>
                        <p className="text-gray-400">Explore real-world POIs to find resources and loot.</p>
                    </div>
                    <div className="bg-slate-grey p-6 rounded-2xl border border-white/5">
                        <img src="/images/gameplay_concept_base.png" alt="Base Building" className="w-full h-48 object-cover rounded-lg mb-4" />
                        <h3 className="text-2xl font-bold mb-2">Build & Survive</h3>
                        <p className="text-gray-400">Construct shelters and defend your resources.</p>
                    </div>
                </div>
            </div>

            <div id="ai-story" className="py-20 bg-slate-grey/30">
                <div className="container mx-auto px-6 flex flex-col md:flex-row items-center gap-12">
                    <div className="flex-1">
                        <img src="/images/ai_matrix_code.png" alt="AI Code" className="rounded-2xl shadow-2xl border border-neon-cyan/20" />
                    </div>
                    <div className="flex-1">
                        <span className="text-neon-cyan font-mono text-sm tracking-widest mb-2 block">BEHIND THE SCENES</span>
                        <h2 className="text-4xl font-bold mb-6">100% AI Developed</h2>
                        <p className="text-gray-300 text-lg mb-6">
                            Every line of code, every mechanic, and every pixel of logic was generated by Claude Code.
                            54,526 lines of code written in just 3 weeks by a single developer.
                        </p>
                        <div className="grid grid-cols-2 gap-6">
                            <div className="border-l-2 border-neon-cyan pl-4">
                                <div className="text-3xl font-bold text-white">3 Weeks</div>
                                <div className="text-sm text-gray-400">Development Time</div>
                            </div>
                            <div className="border-l-2 border-neon-cyan pl-4">
                                <div className="text-3xl font-bold text-white">54k+</div>
                                <div className="text-sm text-gray-400">Lines of Code</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Home;
